### PR TITLE
ENH: Implementation of getResults endpoint

### PR DESCRIPTION
**Pull request by stsievert**
This will give access to results (e.g., embeddings for different algorithms) and algorithm timing information.

We already have a `get_stats` endpoint, but this separates the visualization and obtaining the results. In the future, `myApp` can call `app.getResults`. I've refactored the DuelingBandits dashboard to call this function, it is simpler.

- [x] Implement API endpoint to get at `/api/experiment/[exp-uid]/getResults`
    * This endpoint it a GET endpoint (and does not accept any arguments)
    * This endpoint returns a JSON object unless `?csv=1` (in which case it returns a zip file)
    * This endpoint eventually calls myApp.getResults with the `model` returned from myApp.getModel
- [x] The dashboard links include links to download all models in JSON and CSV format
- [x] Test

screen shot 2017-06-07 at 6 02 31 pm

### CODE REVIEW

**Comment by stsievert** [comment]
This code is ready for review.

I have tested

* YAML arguments (by generation of docs at `/assistant/doc/[app-id]/pretty`
* Download under all default apps
    * tested download of JSON, formatted JSON and CSV
    * (not implemented for pooling bandits binary classifications)

**Comment by stsievert** [comment]
LGTM. Ready to merge IMO.

**Comment by lalitkumarj** [comment]
Scott and I discussed. He is going to be putting this into the Triplets code directly instead of having a different endpoint.

**Comment by stsievert** [comment]
Yeah, this PR is too large. All work should be done client side; we already have the necessary endpoints.

**Pull request closed without merging**
