### PR TITLE
Clean up experiment launching (local/launch.py)

### PR DESCRIPTION
**Pull request by liamim**
Changes made:
* Fixed faulty external data target logic
* Cleaned up API payload encoder
* Reduced spurious debug output

The refactored encoder was checked against the output of the original.

### CODE REVIEW

**Comment by dconathan** [comment]
Should the analogous changes be made to https://github.com/nextml/NEXT/blob/master/examples/launch.py ?

**Comment by lalitkumarj** [comment]
Everything around launch.py seems broken and bad. We used to have a much simpler system where people would specify json dictionaries to be posted. I would like this to come back.

Questions for Scott:
1. Why is there a separate examples in local vs in the top level?
2. why does test_examples not work?

**Comment by stsievert** [comment]
> Why is there a separate examples in local vs in the top level?

I think that's left over. I don't see a reason they're separate, I launch the examples on local.

> why does test_examples not work?

It works for me.

> We used to have a much simpler system where people would specify json dictionaries to be posted

Much simpler on NEXT or on the local machine? Folding the local launch script (`launch_expirement.py`?) into a new API endpoint allowed for GUI launch. The old endpoint still exists and can still be hit, maybe we should have an example with this.

**Comment by lalitkumarj** [comment]
Still not working for me...a bit afraid a docker update broke things.

Liam: The point of the json system was that so users could do logic in a
launch script and build the dictionaries for an initExp a bit more
carefully. Gui launch is nice if you are doing things in a vanilla way but
basically 100% of my applications require custom launch scripts. For
example, say you need to launch 100 custom experiments and then have a
query page that rotates between them? I am not about to create 100 yaml
files. NEXT is restful and should be basically used that way by people who
know what they are doing.

It's nice to create a python dictionary and then just post it. I'm also
kind of against the GUI launch right now - it doesn't work and it
obfuscates what's actually happening with the targets. I think we can
probably do things to make it work in the long run...but that's a longer
issue.

It's not much work to bring this back - I've discussed it with Scott. We
can just have a launch-yaml.py file and a launch-json.py file.

Also:

   - local/launch.py: Clean up backend fetching
   - local/launch.py: remove spurious call to print (echoing passed args)
   - local/launch.py: Clean up experiment/dashboard URL reporting
   - local/launch.py: Clean up API payload encoder
   - local/launch.py: Fix faulty external data-targets logic

What do all of those mean? Especially the third one?

**Comment by dconathan** [comment]
re: docker since a recent docker update, I've found myself having to reboot every once and a while because docker is acting up (restarting docker daemon does not help).  Hopefully this a simple docker bug that gets fixed soon.

**Comment by liamim** [comment]
Yes, I've been having Docker issues as well.
@lalitkumarj 1) clean up the code to fetch the backend uri 
2) what it says on the box
3) clean up the logging of the dashboard/experiment urls
4) again, exactly what it says
5) fix the logic when creating dict keys if an external target.json is passed

**Comment by liamim** [comment]
The script printed out some information about where you'd need to go to
find the launched experiment. I slightly changed that formatting; in
retrospect it probably wasn't necessary to mention that.
The payload encoder packs the experiment launch dict into a base-64 encoded
blob with a header describing the length of each component blob. I talked
to Scott about this last week and we agreed this definitely isn't the most
elegant way to pass data, and should probably be replaced.

wrt experiments having separate launch scripts: that makes total sense if
you have the knowledge necessary to *write* or modify launch scripts for
your experiments.
For non-technical users of NEXT, having a GUI/YAML manifest launch system
is probably preferable. Like Scott said, it's not much trouble to maintain
separate endpoints.

Liam

**Comment by lalitkumarj** [comment]
Awesome thanks!!

**Pull request merged**
