### PR TITLE
Give Butler.Collections and Butler.Memory the python dict-api

### PR DESCRIPTION
**Pull request by dconathan**
Allows you to use dict-like api for Collections.  e.g. `butler.experiment["foo"] = "bar"` instead of `butler.experiment.set(key="foo", value="bar")`.

New tests in Tests app to test this.

I also refactored the Tests app a little more.  It probably could be cleaned up a bunch more to do more unit test-y things but it's good for now.

### CODE REVIEW

**Comment by dconathan** [comment]
Note that this is purely syntatic sugar on top of old api... should be 100% backwards compatible.

**Comment by lalitkumarj** [comment]
It looks good to me. Liam - can you take a look over this to confirm?

**Comment by liamim** [comment]
LGTM! I'd advise putting tests of the Collections stuff in [`test_collection.py`](https://github.com/nextml/NEXT/blob/master/next/apps/tests/test_collection.py), since that's where all the other tests for `Collection` are currently.

**Comment by lalitkumarj** [comment]
Have we gone and moved all the old apps to using this? I would want that done before putting it into a release.

**Comment by liamim** [comment]
Not afaik. I'd ping Devin.

Liam

**Comment by dconathan** [comment]
Old apps were not updated.  This was a backwards compatible change.

**Pull request merged**
