### PR TITLE
Futurization [WIP]

### PR DESCRIPTION
**Pull request by liamim**
This PR `futurizes` the NEXT codebase.
By using futurization and not just `2to3`, the codebase can run on both Python 3 and Python 2.

### CODE REVIEW

**Comment by stsievert** [comment]
docopt is used in [`launch.py`](https://github.com/nextml/NEXT/blob/1f388a59e2316a5baefbec8872dcddac4410337f/examples/launch.py#L31)

Does futurize look at types of different variables to see if it should use integer division?

**Comment by liamim** [comment]
The path to `next/lib` is added to the import path [in `launch.py`](https://github.com/nextml/NEXT/blob/1f388a59e2316a5baefbec8872dcddac4410337f/examples/launch.py#L30).

I've not touched `apps/` yet; all the division in `next/` I worked out on a case-by-case basis. `future` does provide an `old_div` function, which `futurize` inserts as a temporary measure to make sure code continues to work.

**Comment by stsievert** [comment]
> The path to next/lib is added to the import path in launch.py; there's a copy of docopt there.

:+1:

> an old_div function

Which means the code will be littered with `old_div` calls. We'll have to do it manually to avoid this.

**Comment by liamim** [comment]
Yep; it's just used as a stopgap measure. I thought you might want to know
that it won't do anything dangerous automatically.

Liam

**Comment by liamim** [comment]
I've got the main backend/frontend app starting on Python 3; still working out some Unicode issues.

**Comment by liamim** [comment]
Pjiemont is creating very annoying porting issues.

**Comment by stsievert** [comment]
Pijemont's source is here https://github.com/daniel3735928559/pijemont

It does look like there is a Python 3 implementation at `verifiers.py`. The diff between `verifier.py` and `verifier2.py` is

``` diff
↪  diff verifier.py verifier2.py
177,178c177,178
<         if not isinstance(input_element, (int, float)):
<             if isinstance(input_element, (str)):
---
>         if not isinstance(input_element, (int, float, long)):
>             if isinstance(input_element, (str, unicode)):
195c195
<         if not isinstance(input_element, (str)):
---
>         if not isinstance(input_element, (str, unicode)):
```

**Pull request closed without merging**
