### PR TITLE
Fixes #161, some bugs with non-8000 port

### LINKED ISSUE #161: Dashboard won't load with non-8000 port.
I've tested this with various ports (8888, 8080, etc.) and getting the same errors every time.  /home, dashboard/experiment_list, and queries pages load fine, but dashboard throws this error:

```
nextbackenddocker_1  | Exception on /dashboard/experiment_dashboard/50f15481fdcf2661da692a155c5a66/RocketClassification [GET]
nextbackenddocker_1  | Traceback (most recent call last):
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
nextbackenddocker_1  |     response = self.full_dispatch_request()
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
nextbackenddocker_1  |     rv = self.handle_user_exception(e)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
nextbackenddocker_1  |     return original_handler(e)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
nextbackenddocker_1  |     return original_handler(e)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
nextbackenddocker_1  |     return original_handler(e)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
nextbackenddocker_1  |     reraise(exc_type, exc_value, tb)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
nextbackenddocker_1  |     rv = self.dispatch_request()
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
nextbackenddocker_1  |     return self.view_functions[rule.endpoint](**req.view_args)
nextbackenddocker_1  |   File "/next_backend/next/dashboard/dashboard.py", line 144, in experiment_dashboard
nextbackenddocker_1  |     exceptions_present=exceptions_present(exp_uid, host_url),
nextbackenddocker_1  |   File "/next_backend/next/dashboard/dashboard.py", line 152, in exceptions_present
nextbackenddocker_1  |     r = requests.get(url)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
nextbackenddocker_1  |     return request('get', url, params=params, **kwargs)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
nextbackenddocker_1  |     return session.request(method=method, url=url, **kwargs)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
nextbackenddocker_1  |     resp = self.send(prep, **send_kwargs)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
nextbackenddocker_1  |     r = adapter.send(request, **kwargs)
nextbackenddocker_1  |   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
nextbackenddocker_1  |     raise ConnectionError(e, request=request)
nextbackenddocker_1  | ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/experiment/50f15481fdcf2661da692a155c5a66/logs/APP-EXCEPTION (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f8f3b8bed10>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

### PR DESCRIPTION
**Pull request by dconathan**
Makes it so if you specify a different `NEXT_BACKEND_GLOBAL_PORT` in `docker_up.sh`, those changes carry through the appropriate places in the `docker-compose.yml` file.

One thing is to note is that one has to manually set the `NEXT_BACKEND_GLOBAL_PORT` environment variable when launching an experiment (still defaults to 8000), since presumably that it is in a new environment.  We could fix this by making a separate `setup.sh` or `config.sh` script that sets all the environment variables, which `docker_up.sh` and `experiment_triplet.py`, etc. could then source...

### CODE REVIEW

**Comment by dconathan** [comment]
Hold off on merging this until we discuss #161...

**Comment by stsievert** [comment]
We also need to hold off merging because of #154 in which we delete `experiment_triplet.py` and move to a new endpoint for initializing the examples.

From the files changed I can't tell what happens when `NEXT_BACKEND_GLOBAL_PORT` isn't defined in `docker_up.sh`. It looks like if the environment variable isn't defined the browser will try to render `localhost:`.

**Comment by dconathan** [comment]
Right didn't think about that... if not defined in `docker_up.sh`, `next.constants` will still grab the default `localhost:8000` but `docker-compose.yml` will be all effed up.

**Comment by dconathan** [comment]
This is out of date and conflicts with #166. closing

**Pull request closed without merging**
